# █▀▄ █▀▀ █▀▀ █▀█ █▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█
# █▄▀ ██▄ █▄▄ █▄█ █▀▄ █▀█ ░█░ █ █▄█ █░▀█

decoration {
  # █▀█ █▀█ █░█ █▄░█ █▀▄   █▀▀ █▀█ █▀█ █▄░█ █▀▀ █▀█
  # █▀▄ █▄█ █▄█ █░▀█ █▄▀   █▄▄ █▄█ █▀▄ █░▀█ ██▄ █▀▄
  rounding = 0

  # █▄▄ █░░ █░█ █▀█
  # █▄█ █▄▄ █▄█ █▀▄
  blur {
      enabled = false
      size = 6
      passes = 3
      new_optimizations = true
      ignore_opacity = true
      xray = false
  }


  # █▀ █░█ ▄▀█ █▀▄ █▀█ █░█░█
  # ▄█ █▀█ █▀█ █▄▀ █▄█ ▀▄▀▄▀
  shadow {
    enabled = false
    ignore_window = true
    offset = 1 1
    range = 1
    render_power = 4
    color = $secondary
  }
}

# █▀▀ █▀▀ █▄░█ █▀▀ █▀█ ▄▀█ █░░
# █▄█ ██▄ █░▀█ ██▄ █▀▄ █▀█ █▄▄
general {
    gaps_in = 2
    gaps_out = 0
    border_size = 0

    # col.active_border = $primary
    # col.inactive_border = $on_secondary
}

group {
    # col.border_active = $primary $on_primary_container 45deg
    # col.border_inactive = $on_secondary $secondary_container 45deg
    # col.border_locked_active = $primary $on_primary_container 45deg
    # col.border_locked_inactive = $on_secondary $secondary_container 45deg
    groupbar {
      gradients = false
      col.active = $primary
      col.inactive = $tertiary_container
    }
}
