# █▄▀ █▀▀ █▄█ █▄▄ █ █▄░█ █▀▄
# █░█ ██▄ ░█░ █▄█ █ █░▀█ █▄▀

#!
##! Shell
# These absolutely need to be on top, or they won't work consistently
bindd = Super, D, Toggle overview, global, quickshell:overviewToggleRelease # Toggle overview/launcher
# bind = Super, Super_L, exec, qs ipc call TEST_ALIVE || pkill fuzzel || fuzzel # [hidden] Launcher (fallback)
# binditn = Super, catchall, global, quickshell:overviewToggleReleaseInterrupt # [hidden]
# bind = Ctrl, Super_L, global, quickshell:overviewToggleReleaseInterrupt # [hidden]
bind = Super, mouse:272, global, quickshell:overviewToggleReleaseInterrupt # [hidden]
bind = Super, mouse:273, global, quickshell:overviewToggleReleaseInterrupt # [hidden]
bind = Super, mouse:274, global, quickshell:overviewToggleReleaseInterrupt # [hidden]
bind = Super, mouse:275, global, quickshell:overviewToggleReleaseInterrupt # [hidden]
bind = Super, mouse:276, global, quickshell:overviewToggleReleaseInterrupt # [hidden]
bind = Super, mouse:277, global, quickshell:overviewToggleReleaseInterrupt # [hidden]
bind = Super, mouse_up,  global, quickshell:overviewToggleReleaseInterrupt # [hidden]
bind = Super, mouse_down,global, quickshell:overviewToggleReleaseInterrupt # [hidden]


# █▀▀ █▀█ █░░ █▀█ █▀█ █ █▄░█ ▄▀█ ▀█▀ █▀█ █▀█
# █▄▄ █▄█ █▄▄ █▄█ █▀▄ █ █░▀█ █▀█ ░█░ █▄█ █▀▄
# Random wallpaper change theme
bind = SUPER, T, exec, bash ~/.colors/colorizer.bash -d ~/.wallpapers/ -A
# Switch between dark and light mode
bind = SUPER SHIFT, T, exec, bash ~/.colors/colorizer.bash -S
# Select wallpaper via Zenity dialog
bind = SUPER CTRL, T, exec, bash ~/.colors/colorizer.bash -s
# Reload config (no generation)
bind = SUPER, R, exec, bash ~/.colors/colorizer.bash -r
# Relaunch and set (with generation based on previous settings if no other options specified)
bind = SUPER SHIFT, R, exec, bash ~/.colors/colorizer.bash -R
# Pick color from screen as matugen base color
bind = SUPER SHIFT, C, exec, bash ~/.colors/colorizer.bash -c "$(hyprpicker)"

# █▀█ █░█ █ █▀▀ █▄▀ █▀ █░█ █▀▀ █░░ █░░
# ▀▀█ █▄█ █ █▄▄ █░█ ▄█ █▀█ ██▄ █▄▄ █▄▄
bindit = ,Super_L, global, quickshell:workspaceNumber # [hidden]
bindd = Super, V, Clipboard history >> clipboard, global, quickshell:overviewClipboardToggle # Clipboard history >> clipboard
# bindd = Super, Period, Emoji >> clipboard, global, quickshell:overviewEmojiToggle # Emoji >> clipboard
# bindd = Super, Tab, Toggle overview, global, quickshell:overviewToggle # [hidden] Toggle overview/launcher (alt)
bindd = Super, A, Toggle left sidebar, global, quickshell:sidebarLeftToggle # Toggle left sidebar
bind = Super+Alt, A, global, quickshell:sidebarLeftToggleDetach # [hidden]
# bind = Super, B, global, quickshell:sidebarLeftToggle # [hidden]
# bind = Super, O, global, quickshell:sidebarLeftToggle # [hidden]
bindd = Super, N, Toggle right sidebar, global, quickshell:sidebarRightToggle # Toggle right sidebar
bindd = Super, Slash, Toggle cheatsheet, global, quickshell:cheatsheetToggle # Toggle cheatsheet
# bindd = Super, K, Toggle on-screen keyboard, global, quickshell:oskToggle # Toggle on-screen keyboard
bindd = Super Shift, M, Toggle media controls, global, quickshell:mediaControlsToggle # Toggle media controls
bindd = Ctrl+Alt, Delete, Toggle session menu, global, quickshell:sessionToggle # Toggle session menu
bind = Ctrl+Alt, Delete, exec, qs ipc call TEST_ALIVE || pkill wlogout || wlogout -p layer-shell # [hidden] Session menu (fallback)
bind = Shift+Super+Alt, Slash, exec, qs -p ~/.config/quickshell/welcome.qml # [hidden] Launch welcome app
