# █▄▀ █▀▀ █▄█ █▄▄ █ █▄░█ █▀▄
# █░█ ██▄ ░█░ █▄█ █ █░▀█ █▄▀


# █▀▀ █▀█ █░░ █▀█ █▀█ █ █▄░█ ▄▀█ ▀█▀ █▀█ █▀█
# █▄▄ █▄█ █▄▄ █▄█ █▀▄ █ █░▀█ █▀█ ░█░ █▄█ █▀▄
# Random wallpaper change theme
bind = SUPER, T, exec, bash ~/.colors/colorizer.bash -d ~/.wallpapers/ -M
# Switch between dark and light mode
bind = SUPER SHIFT, T, exec, bash ~/.colors/colorizer.bash -s
# Reload config
bind = SUPER, R, exec, bash ~/.colors/colorizer.bash -r
# Reload config
bind = SUPER SHIFT, R, exec, bash ~/.colors/colorizer.bash -R
# Pick color from screen as matugen base color
bind = SUPER SHIFT, C, exec, bash ~/.colors/colorizer.bash -c "$(hyprpicker)" -m "dark"


# ▄▀█ █▀▀ █▀
# █▀█ █▄█ ▄█
bind = SUPER, N, exec, ags request file_explorer:toggle
bind = SUPER, D, exec, ags request statusline:toggle:appLauncher
bind = SUPER, semicolon, exec, ags request statusline:toggle:command
bind = SUPER SHIFT, W, exec, ags request statusline:toggle:wallpapers
